### ISSUE TITLE
트라비스에서 빌드한 도커 이미지를 실행하면 에러가 생긴다.

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/auth-api#26]
로이 맥에서 빌드하면 정상적으로 작동한다.

```
/parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require': libruby.so.2.3: cannot open shared object file: No such file or directory - /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/nokogiri.so (LoadError)
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri.rb:25:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/sanitize_helper.rb:2:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/text_helper.rb:32:in `<module:TextHelper>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/text_helper.rb:29:in `<module:Helpers>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/text_helper.rb:6:in `<module:ActionView>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/text_helper.rb:4:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/form_tag_helper.rb:6:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers/form_helper.rb:4:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers.rb:50:in `<module:Helpers>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers.rb:4:in `<module:ActionView>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/helpers.rb:3:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/base.rb:5:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionview/lib/action_view/view_paths.rb:1:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionpack/lib/abstract_controller/rendering.rb:4:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionpack/lib/action_controller/base.rb:204:in `<class:Base>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionpack/lib/action_controller/base.rb:164:in `<module:ActionController>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/actionpack/lib/action_controller/base.rb:5:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/health_check-1.5.1/lib/health_check/health_check_controller.rb:5:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/health_check-1.5.1/lib/health_check/health_check_controller.rb:5:in `<module:HealthCheck>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/health_check-1.5.1/lib/health_check/health_check_controller.rb:4:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/health_check-1.5.1/lib/health_check.rb:48:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/gems/health_check-1.5.1/lib/health_check.rb:48:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /parti/auth-api/config/application.rb:17:in `<top (required)>'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/command.rb:20:in `run'
	from /parti/auth-api/vendor/bundle/ruby/2.3.0/bundler/gems/rails-4feb34ddf291/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by phi4grv** [comment]
CI 서버를 Shippable로 이전하고 업로드에 성공했다. #46
